// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          string `json:"id" bson:"_id"`
	Name        string `json:"name" bson:"name"`
	Style       string `json:"style" bson:"style"`
	Description string `json:"description" bson:"description"`
	Price       int    `json:"Price" bson:"Price"`
}

type NewItem struct {
	Name        string `json:"name" bson:"name"`
	Style       string `json:"style" bson:"style"`
	Description string `json:"description" bson:"description"`
	Price       int    `json:"Price" bson:"Price"`
}
